config/routes.rb
Rails.application.routes.draw do

  get 'chats/show'
  devise_for :users

  resources :users, only: [:show,:index,:edit,:update] do
    get :followings, on: :member
    get :followers, on: :member
  end
  resources :relationships, only: [:create, :destroy]
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  root 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search', to: 'searchs#search'
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow, dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user, dependent: :destroy

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  has_many :group_users   #ここ！
  has_many :groups, through: :group_users

  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]


  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user)
    @relationship = current_user.relationships.find_by(follow_id: @user.id)
    @new_relationship = current_user.relationships.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @relationship = current_user.relationships.find_by(follow_id: @users.ids)
    @new_relationship = current_user.relationships.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.all
    @relationship = current_user.relationships.find_by(follow_id: @users.ids)
    @new_relationship = current_user.relationships.new
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.all
    @relationship = current_user.relationships.find_by(follow_id: @users.ids)
    @new_relationship = current_user.relationships.new
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>
          Following:
          <%= link_to followings_user_path(user) do %>
            <%= user.followings.count %>
          <% end %>
        </td>
        <td>
          Followers:
          <%= link_to followers_user_path(user) do %>
            <%= user.followers.count %></td>
          <% end %>
        <% if current_user == user %>
          <td></td>
        <% else %>
          <td><%= render 'relationships/follow_form', user: user %></td>
        <% end %>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>following</th>
    <th><%= user.followings.count %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= user.followers.count %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "form-group btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

<div>
  <% unless current_user == user %>
    <div class="form-group">
      <%= render 'relationships/follow_form', user: user %>
    </div>
  <% end %>

  <% if (current_user != user)&&(current_user.following?(user))&&(user.following?(current_user))  %>
    <div class= "btn btn-success btn-block">
      <%= link_to 'Begin Chat', chat_path(user.id) %>
    </div>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @nbook %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Followers</h2>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @nbook %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Followings</h2>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @nbook %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <div>
        <%=link_to "グループを作成する",new_group_path %>
        | <%=link_to "グループ一覧",groups_path %>
      </div>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @nbook %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <div class = "table_width">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今日の投稿数</th>
              <th>前日の投稿数</th>
              <th>前日比</th>
            </tr>
          </thead>
        <tbody>
          <tr>
         　  <td><%= @today_book.count %></td>
         　  <td><%= @yesterday_book.count %></td>
            <td>
             <% if @yesterday_book.count == 0 %>
              前日の投稿はありません
             <% else %>
             　<% @the_day_before =   @today_book.count / @yesterday_book.count.to_f  %>
             　<%= (@the_day_before * 100).round %>
             <% end %>
            </td>
          </tr>
        </tbody>
       </table>
      <div class = "table_width">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今週の投稿数</th>
              <th>先週の投稿数</th>
              <th>先週比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
           　  <td><%= @this_week_book.count %></td>
           　  <td><%= @last_week_book.count %></td>
              <td>
              　<% if @last_week_book.count == 0 %>
                　先週の投稿はありません
              　<% else %>
               　　<% @the_week_before =    @this_week_book.count / @last_week_book.count.to_f  %>
               　　<%= (@the_week_before * 100).round %>
              　<% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>